import fs from "node:fs"
import path from "node:path"

const configName = "electron-builder.evil.config.ts"

type ReleaseRepository = {
  owner: string
  repo: string
}

function parseRepository(value: string): ReleaseRepository {
  const match = /^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/.exec(value)
  if (!match) throw new Error(`Expected GitHub repository in owner/repo form, received: ${value}`)
  return { owner: match[1], repo: match[2] }
}

export function writeElectronReleaseConfig(root: string, repository: string) {
  const desktop = path.join(root, "packages/desktop")
  const upstreamConfig = path.join(desktop, "electron-builder.config.ts")
  const packageJson = path.join(desktop, "package.json")

  if (!fs.existsSync(upstreamConfig) || !fs.existsSync(packageJson)) {
    throw new Error("Current upstream checkout does not expose the expected Electron desktop package")
  }

  const source = fs.readFileSync(upstreamConfig, "utf8")
  const pkg = JSON.parse(fs.readFileSync(packageJson, "utf8")) as { scripts?: Record<string, string> }
  if (!source.includes("electron-builder") || !pkg.scripts?.build || !pkg.scripts?.package) {
    throw new Error("Unknown desktop packaging layout; refusing to generate an Electron release override")
  }

  const { owner, repo } = parseRepository(repository)
  const output = path.join(desktop, configName)
  fs.writeFileSync(
    output,
    `// Generated by evil-opencode CI. Keep upstream Electron packaging, but make this fork unsigned and self-updating.
import upstreamConfig from "./electron-builder.config"

const base = upstreamConfig as Record<string, any>

export default {
  ...base,
  mac: {
    ...(base.mac ?? {}),
    identity: null,
    hardenedRuntime: false,
    notarize: false,
  },
  dmg: {
    ...(base.dmg ?? {}),
    sign: false,
  },
  win: {
    ...(base.win ?? {}),
    signtoolOptions: {
      sign: async () => undefined,
    },
  },
  publish: {
    provider: "github",
    owner: ${JSON.stringify(owner)},
    repo: ${JSON.stringify(repo)},
    channel: "latest",
  },
}
`,
  )
  return output
}

if (import.meta.main) {
  const [root, repository] = Bun.argv.slice(2)
  if (!root || !repository) {
    throw new Error("Usage: bun script/write-opencode-electron-release-config.ts <upstream-root> <owner/repo>")
  }
  console.log(writeElectronReleaseConfig(root, repository))
}
